const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";
const CHANGE_ITEM = "CHANGE_ITEM";
const CHANGE_STORE = "CHANGE_STORE";
const CLEAR_LIST = "CLEAR_LIST";


export { ADD_ITEM, DELETE_ITEM, CHANGE_ITEM, CHANGE_STORE };
